version: '3'
services:
  node-app:
    build: 
      # specifies location of docker file
      context: .
      # pass in arguments
      args:
        NODE_ENV: development
    volumes:
     - ./:/app
     - /app/node_modules
    environment:
     - NODE_ENV=development
     - MONGO_USER=james
     - MONGO_PASSWORD=pass
    command: npm run dev
  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=james
      - MONGO_INITDB_ROOT_PASSWORD=pass