version: '3'
services:
  nginx:
    ports:
      -"80:80"
  node-app:
    build: 
      # specifies location of docker file
      context: .
      # pass in arguments
      args:
        NODE_ENV: production
    environment:
      - NODE_ENV=production
    command: node index.js